### ISSUE TITLE
Feature request: Searchable list of hosts  

### ISSUE THREAD

**Issue by supaflybro** [jocafamaka/nagmapReborn#10]
It would be nice to have opportunity to enable old nagmap like sidebar with list of all hosts (it can be without host status visualization). Because of large installations we have, about 1000-3000 if host, searching specific host is problematic.

**Comment by jocafamaka** [comment]
A search field can be added at the top of the hosts listing when you enable ChangesBar in mode 2, but I do not want to go back to the old style with the sidebar, at least not in the near future.

This new feature will be added in release 1.6.1.

Thank you for your collaboration.

**Comment by jocafamaka** [comment]
On [v1.6.1](https://github.com/jocafamaka/nagmapReborn/releases/tag/v1.6.1) of NagMap Reborn your request has been implemented.

Thank you for your time and collaboration.
