### ISSUE TITLE
Feature request - Bounce time depending of status

### ISSUE THREAD

**Issue by xvx45** [jocafamaka/nagmapReborn#14]
Does a configuration to set bouncing time for each status is possible ?

eg : 
- Warning = XX sec.
-  Critical = XX sec.
etc..

Regards,

**Comment by jocafamaka** [comment]
At the moment I do not intend to enter this level of detail.
The configuration file has far more "options" than I initially wanted it to have.

This idea is in interesting parts, in the future maybe I can do a js file, which makes it possible to change the characteristics of some animations, but at the moment I will not be doing this implementation.

Thank you for your collaboration.
