### ISSUE TITLE
Connection to icinga2 api

### ISSUE THREAD

**Issue by elderorange** [jocafamaka/nagmapReborn#15]
There are plans to get a connection to icinga2 api?

**Comment by jocafamaka** [comment]
At the moment I really do not have any in-depth knowledge about the API of Icinga<sup>2</sup>, unfortunately I do not have enough free time to do an implementation for compatibility tests.

If you are interested in such compatibility, please contact me by e-mail: joao_carlos.r@hotmail.com

And with your collaboration, **maybe** we can make it happen.

Thank you for your collaboration.
