### ISSUE TITLE
Google API Key required

### ISSUE THREAD

**Issue by robertocandelu** [jocafamaka/nagmapReborn#3]
Starting on June 11, 2018, you’ll need a valid API key and a billing account to access Google APIs
https://cloud.google.com/maps-platform/user-guide/account-changes/#no-plan

How can insert my private API key?
Thank you.
regards

**Comment by jocafamaka** [comment]
Hey,

Now with the [v1.4.1](https://github.com/jocafamaka/nagmapReborn/releases/tag/v1.4.1) of NagMap Reborn you can insert your API key directly into the configuration file.

Thank you for your collaboration!
