### ISSUE TITLE
Nagmap question

### ISSUE THREAD

**Issue by CrinaPanturu** [jocafamaka/nagmapReborn#32]
Hello! Is it possible to change the icons shown on nagmap 1.6 based on hostgroup? For example I have routers & switches hostgroups . As it is configured now, I see them shown with a green bullet(if they are reachable) but I want them to be shown differently, for example routers with light green/blue/or anything else and switches with green/dark blue/etc. This way makes it easier to see and identify where are the routers and the switches situated on the map.  Thank you!

**Comment by jocafamaka** [comment]
Hello.

Unfortunately, this functionality is not available at the moment.

It is currently under development and will be released only in version 2.0.1, as described [here](https://github.com/jocafamaka/nagmapReborn/wiki/How-to-create-an-icon-style%3F#the-other-nodes).

In addition, I inform you that the addition of new features for version 1.6.4 (and below) ended in March 2019 ([see here](https://github.com/jocafamaka/nagmapReborn/tree/v1.6.4#hiatus-notice)), and support ended in July 2020 with the release of version 2.0.0.

Regards.
