### ISSUE TITLE
Disable leaflet-interactive

### ISSUE THREAD

**Issue by billzeta** [jocafamaka/nagmapReborn#33]
Feature request ::

- Config variable to toggle on/off setting the leaflet-interactive css class for hosts. Certain users do not need to see the additional information just whether a host is up/down.

**Comment by jocafamaka** [comment]
Hello, sorry for the long delay!!!
I haven't had much time to focus on this project, unfortunately.

This functionality may be added in future updates, but at the moment I don't want to add another configuration variable.

But this would be an extension of the current option <code>update_animation</code>, which would be transformed into an option that makes the application lighter, with less animations...

For the moment keep this issue open.
