### ISSUE TITLE
Service alerts

### ISSUE THREAD

**Issue by rozikjan** [jocafamaka/nagmapReborn#35]
Hello,

I am using Nagios Core 4.3.4 with nagmap reborn 2.0. The hosts alerts are displayed but no services alerts. What could be wrong?

**Comment by jocafamaka** [comment]
Hello, sorry for the long delay!!

At the moment Nagmap Reborn can only represent and track one service per host, so you need to choose which one you want to track.

You can do this by definig the <code>filter_service</code> in the config file L72 [here](https://github.com/jocafamaka/nagmapReborn/blob/fabb5e6f43756f801072eb5b9c2a3dd0fdf66f96/config.php.example#L72).

That way the application will track that service to define the status show in the map.
