### ISSUE TITLE
Fazendo o painel de notificações ficar na vertical ao invés da horizontal

### ISSUE THREAD

**Issue by edulbastos** [jocafamaka/nagmapReborn#36]
Olá,

Antes de mais nada, parabéns pelo excelente trabalho no NagMapv2 Reborn. Gostaria de saber se é possível ter o painel de notificações ser posicionado lateralmente ao invés de horizontalmente. Isso faria com que a organização da tela ficasse melhor no meu caso.

Obrigado,

Eduardo Bastos

**Comment by jocafamaka** [comment]
Olá,

Primeiramente desculpe pela demora e obrigado!!

Atualmente existe um modo lateral da barra de alertas, fazendo com que a mesma fique posicionada no lado direito da tela.

Você pode habilitar essa funcionalidade através do arquivo de configurações.

Definindo a opção <code>mode</code> para 3 [(aqui)](https://github.com/jocafamaka/nagmapReborn/blob/fabb5e6f43756f801072eb5b9c2a3dd0fdf66f96/config.php.example#L80)
```PHP
'mode' => 3,
```

Qualquer dúvida só chamar!
