### ISSUE TITLE
Failed to initialize class!

### ISSUE THREAD

**Issue by ruisgoncalves** [jocafamaka/nagmapReborn#38]
Hello,
I tried to install nagmap 2.0 version.
I followed the installation process but first launching the website, I got the following error :

Failed to initialize class!

Details: ReferenceError: Host is not defined

Stack: ReferenceError: Host is not defined at NagmapReborn.getHosts (http://172.27.170.30/mapcont2/resources/js/classes/NagmapReborn.js?v=2.0.0:216:32) at new NagmapReborn (http://172.27.170.30/mapcont2/resources/js/classes/NagmapReborn.js?v=2.0.0:37:31) at http://172.27.170.30/mapcont2/resources/js/app.js?v=2.0.0:211:35

I've only 1 host defined as described above

################################################################
define hostgroup{
	hostgroup_name	P_ROUTER
	alias			PROPROUTER
	}

define host{
host_name		P_E0000_GTW-AS
address			192.168.0.1
hostgroups			P_ROUTER
max_check_attempts		10
check_period			24x7
contact_groups			admins
notification_period		24x7
notification_interval		30
notes <latlng>43.213687,-17.81039</latlng>
}
################################################################

I'll appreciate your help

Many thanks in advance / Muito obrigado

**Comment by jocafamaka** [comment]
We just released a new version [v2.1.0](https://github.com/jocafamaka/nagmapReborn/releases/tag/v2.1.0), if you're still interested, try this nes version.
