### ISSUE TITLE
Information Request for how to add Leaflet Plugins to the new code design

### ISSUE THREAD

**Issue by TechCowboy77** [jocafamaka/nagmapReborn#42]
Firstly, PHP and JS are not my strong suits. With your separation of front-end and back-end coding, I am having trouble applying leaflet plugins. 

I can easily add new script sources but find it confusing when attempting to get the control to display on the map as they do not appear. I have tried many placements from directly in the index.php to adding a new div id or layers in the js code. 

In particular, I am attempting to add the Leaflet-radar plugin in order to show severe storm paths in relation to the marked sites. 

If you could tell me which files I need to modify for the plugin to display correctly I would appreciate it. 

Any assistance would be greatly appreciated, included is the link to the plugin.

https://github.com/rwev/leaflet-radar

**Comment by jocafamaka** [comment]
Hi.

You can try the following:

- Add the dependecies (css/js) in the file `index.php`:
  - css after line: https://github.com/jocafamaka/nagmapReborn/blob/25de31e4e682d52cd236c4d36a9329f6e1eddef7/index.php#L21
  - js after line: https://github.com/jocafamaka/nagmapReborn/blob/25de31e4e682d52cd236c4d36a9329f6e1eddef7/index.php#L132

- Add the initialization of the plugin in file `resources/js/NagmapReborn.js`:
  - This can be done after line: https://github.com/jocafamaka/nagmapReborn/blob/25de31e4e682d52cd236c4d36a9329f6e1eddef7/resources/js/classes/NagmapReborn.js#L96

That should be enought to the puglin to work, beawere of cache.

> [!IMPORTANT] 
> Shoud be noted that the repository you link is marked as archivied, and thefore is higly probable that is not long workign as intented.

> [!NOTE]  
> This is all the assistance I can give you at the moment, as I'm no longer actively working on this repository.
> If it still doesn't work, I recommend contacting the plugin developer.

**Comment by TechCowboy77** [comment]
Thank you very much for your assistance.
