### ISSUE TITLE
OpenStreetMaps instead of Google Maps

### ISSUE THREAD

**Issue by brent20** [jocafamaka/nagmapReborn#7]
Hello, is it possible to make an option to use OpenStreetMaps instead of Google Maps? In some cases, it is difficult to obtain a Google Maps key due to the credit card requirement now, OSM will suffice for some users who are unable to go the Google Maps route.
Thanks!

**Comment by jocafamaka** [comment]
As described here:
* [Can I use another API in NagMap Reborn?](https://github.com/jocafamaka/nagmapReborn/wiki/Can-I-use-another-API-in-NagMap-Reborn%3F) 

Unfortunately it is not feasible to do this migration.

**Comment by jocafamaka** [comment]
It is worth remembering that Google gives a $200 monthly credit for free use of the API, as NagMap Reborn is used internally, this is much more than enough, so you have an idea I make use of this same key in three monitors besides that same key to be used in the [Live Preview](https://jocafamaka.github.io/) of NagMap Reborn and I never came even close to 25% of use of that value.

In addition to using the map itself, this credit can be used for routes and places.

Read [here](https://cloud.google.com/maps-platform/pricing/) about free credit.

**Comment by brent20** [comment]
I can't thank you so much for this! Really saved the day here in our implementation. I fired it up and it worked great out of the box with no other configuration! Thank you again for your time and consideration!
