### ISSUE TITLE
Not working with Cyrillic hostnames.

### ISSUE THREAD

**Issue by supaflybro** [jocafamaka/nagmapReborn#9]
Error I get:
Uncaught SyntaxError: Unexpected token ? (index):131

(index):131 line:
window.x_????????_??????????????????????????????_8_1??????___??_??????????????????_??????????????___10_39_3_38x_pos = new L.latLng(52.541817, 39.581676);

**Comment by jocafamaka** [comment]
Make the clone of the last changes and you will not have more problems.

Thanks for reporting this imcompatibility.

**Comment by supaflybro** [comment]
Thanks a lot! I noticed that № sing is causing a problem too, but i fixed it on my side)
